FROM --platform=linux/amd64 node:18   
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG DATABASE_URL
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG BUCKET_NAME
ARG BUCKET_REGION
ARG CLOUDFRONT_DISTRIBUTION
ARG EMAIL_ADDRESS
ARG EMAIL_JWT_SECRET
ARG EMAIL_PASSWORD
ARG KEY_PAIR_ID_TWO
ARG REDIS_HOST
ARG REDIS_PORT
ARG STRIPE_SECRET_KEY
ARG USER_LOGIN_JWT_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV BUCKET_NAME=$BUCKET_NAME
ENV BUCKET_REGION=$BUCKET_REGION
ENV CLOUDFRONT_DISTRIBUTION=$CLOUDFRONT_DISTRIBUTION
ENV EMAIL_ADDRESS=$EMAIL_ADDRESS
ENV EMAIL_JWT_SECRET=$EMAIL_JWT_SECRET
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV KEY_PAIR_ID_TWO=$KEY_PAIR_ID_TWO
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV USER_LOGIN_JWT_SECRET=$USER_LOGIN_JWT_SECRET
RUN npx prisma generate
RUN npm run build
EXPOSE 3000
CMD npx prisma migrate deploy && npm run start:prod 